HEADERS += \
    $$PWD/addtwonumber/addtwonumber.h \
    $$PWD/containerwithmostwater/containerwithmostwater.h \
    $$PWD/gtest/gtest.h \
    $$PWD/longestpalindromicsubstring/longestpalindromicsubstring.h \
    $$PWD/longestsubstringwithoutrepeatingcharacters/longestsubstringwithoutrepeatingcharacters.h \
    $$PWD/palindromenumber/palindromenumber.h \
    $$PWD/reverseinteger/reverseinteger.h \
    $$PWD/SearchinRotatedSortedArray/SearchinRotatedSortedArray.h \
    $$PWD/twosum/twosum.h \
    $$PWD/FindKClosestElements/findkclosestelements.h \
    $$PWD/TopKFrequentElements/topkfrequentelements.h \
    $$PWD/NextGreaterElementI/nextgreaterelementi.h \
    $$PWD/GrayCode/graycode.h \
    $$PWD/RangeModule/rangemodule.h \
    $$PWD/RotateImage/rotateimage.h \
    $$PWD/PlusOne/plusone.h \
    $$PWD/AddBinary/addbinary.h \
    $$PWD/4Sum/foursum.h \
    $$PWD/3Sum/threesumclass.h \
    $$PWD/3Sum/threesumclass.h \
    $$PWD/ReachingPoints/reachingpoints.h \
    $$PWD/ReverseNodesink-Group/reversenodesinkgroup.h \
    $$PWD/Matrix/matrix.h \
    $$PWD/1-bitAnd2-bitCharacters/onebitcharactersolution.h \
    $$PWD/132Pattern/pattern132.h \
    GasStation/gasstation.h \
    $$PWD/ClimbingStairs/climbingstairs.h

SOURCES += \
    $$PWD/addtwonumber/addtwonumber.cpp \
    $$PWD/addtwonumber/test_addtwonumber.cpp \
    $$PWD/containerwithmostwater/containerwithmostwater.cpp \
    $$PWD/containerwithmostwater/test_containerwithmostwater.cpp \
    $$PWD/gtest/gtest-all.cc \
    $$PWD/gtest/gtest_main.cc \
    $$PWD/longestpalindromicsubstring/longestpalindromicsubstring.cpp \
    $$PWD/longestpalindromicsubstring/test_longestpalindromicsubstring.cpp \
    $$PWD/longestsubstringwithoutrepeatingcharacters/longestsubstringwithoutrepeatingcharacters.cpp \
    $$PWD/longestsubstringwithoutrepeatingcharacters/test_longestsubstringwithoutrepeatingcharacters.cpp \
    $$PWD/palindromenumber/palindromenumber.cpp \
    $$PWD/palindromenumber/test_palindromenumber.cpp \
    $$PWD/reverseinteger/reverseinteger.cpp \
    $$PWD/reverseinteger/test_reverseinteger.cpp \
    $$PWD/SearchinRotatedSortedArray/SearchinRotatedSortedArray.cpp \
    $$PWD/SearchinRotatedSortedArray/test_SearchinRotatedSortedArray.cpp \
    $$PWD/twosum/test_twosum.cpp \
    $$PWD/twosum/twosum.cpp \
    $$PWD/FindKClosestElements/findkclosestelements.cpp \
    $$PWD/FindKClosestElements/test_findkclosestelements.cpp \
    $$PWD/TopKFrequentElements/topkfrequentelements.cpp \
    $$PWD/TopKFrequentElements/test_topkfrequentelements.cpp \
    $$PWD/NextGreaterElementI/nextgreaterelementi.cpp \
    $$PWD/NextGreaterElementI/test_nextgreaterelementi.cpp \
    $$PWD/GrayCode/graycode.cpp \
    $$PWD/GrayCode/test_graycode.cpp \
    $$PWD/RangeModule/rangemodule.cpp \
    $$PWD/RangeModule/test_rangemodule.cpp \
    $$PWD/RotateImage/rotateimage.cpp \
    $$PWD/RotateImage/test_rotateimage.cpp \
    $$PWD/PlusOne/plusone.cpp \
    $$PWD/RangeModule/test_rangemodule.cpp \
    $$PWD/PlusOne/test_plusone.cpp \
    $$PWD/AddBinary/addbinary.cpp \
    $$PWD/AddBinary/test_addbinary.cpp \
    $$PWD/4Sum/foursum.cpp \
    $$PWD/4Sum/test_foursum.cpp \
    $$PWD/3Sum/testthreesumclass.cpp \
    $$PWD/ReachingPoints/test_reachingpoints.cpp \
    $$PWD/Matrix/matrix.cpp \
    $$PWD/Matrix/test_matrix.cpp \
    $$PWD/1-bitAnd2-bitCharacters/onebitcharactersolution.cpp \
    $$PWD/1-bitAnd2-bitCharacters/test_onebitcharactersolution.cpp \
    $$PWD/132Pattern/pattern132.cpp \
    $$PWD/132Pattern/test_pattern132.cpp \
    GasStation/gasstation.cpp \
    GasStation/test_GasStation.cpp \
    $$PWD/ClimbingStairs/climbingstairs.cpp \
    $$PWD/ClimbingStairs/test_ClimbingStairs.cpp
