HEADERS += \
    $$PWD/addtwonumber/addtwonumber.h \
    $$PWD/containerwithmostwater/containerwithmostwater.h \
    $$PWD/gtest/gtest.h \
    $$PWD/longestpalindromicsubstring/longestpalindromicsubstring.h \
    $$PWD/longestsubstringwithoutrepeatingcharacters/longestsubstringwithoutrepeatingcharacters.h \
    $$PWD/palindromenumber/palindromenumber.h \
    $$PWD/reverseinteger/reverseinteger.h \
    $$PWD/SearchinRotatedSortedArray/SearchinRotatedSortedArray.h \
    $$PWD/twosum/twosum.h \
    $$PWD/FindKClosestElements/findkclosestelements.h \
    $$PWD/TopKFrequentElements/topkfrequentelements.h \
    $$PWD/NextGreaterElementI/nextgreaterelementi.h \
    $$PWD/GrayCode/graycode.h \
    $$PWD/RangeModule/rangemodule.h \
    $$PWD/RotateImage/rotateimage.h \
    $$PWD/PlusOne/plusone.h \
    $$PWD/AddBinary/addbinary.h \
    $$PWD/4Sum/foursum.h \
    $$PWD/3Sum/threesumclass.h \
    $$PWD/3Sum/threesumclass.h \
    $$PWD/ReachingPoints/reachingpoints.h \
    $$PWD/ReverseNodesink-Group/reversenodesinkgroup.h \
    $$PWD/Matrix/matrix.h \
    $$PWD/1-bitAnd2-bitCharacters/onebitcharactersolution.h \
    $$PWD/132Pattern/pattern132.h \
    $$PWD/GasStation/gasstation.h \
    $$PWD/ClimbingStairs/climbingstairs.h \
    $$PWD/LongestConsecutiveSequence/longestconsecutivesequencesolution.h \
    $$PWD/3SumClosest/threesumclasscloset.h \
    $$PWD/3SumClosest/threesumclasscloset.h \
    $$PWD/SearchInsertPosition/searchinsertposition.h \
    $$PWD/JumpGame/jumpgame.h \
    $$PWD/SpiralMatrixII/spiralmatrixii.h \
    $$PWD/SpiralMatrix/spiralmatrix.h \
    $$PWD/SearchA2DMatrix/searcha2dmatrix.h \
    $$PWD/SearchA2DMatrixII/searcha2dmatrixII.h \
    $$PWD/Subsets/subsets.h\
    $$PWD/JumpGameII/jumpgameII.h \
    $$PWD/WordSearch/wordsearch.h \
    $$PWD/FirstMissingPositive/firstmissingpositive.h \
    $$PWD/MinimumPathSum/minimumpathsum.h \
    $$PWD/FindMinimumInRotatedSortedArray/findminimuminrotatedsortedarray.h \
    $$PWD/FindMinimumInRotatedSortedArrayII/findminimuminrotatedsortedarrayII.h

SOURCES += \
    $$PWD/addtwonumber/addtwonumber.cpp \
    $$PWD/addtwonumber/test_addtwonumber.cpp \
    $$PWD/containerwithmostwater/containerwithmostwater.cpp \
    $$PWD/containerwithmostwater/test_containerwithmostwater.cpp \
    $$PWD/gtest/gtest-all.cc \
    $$PWD/gtest/gtest_main.cc \
    $$PWD/longestpalindromicsubstring/longestpalindromicsubstring.cpp \
    $$PWD/longestpalindromicsubstring/test_longestpalindromicsubstring.cpp \
    $$PWD/longestsubstringwithoutrepeatingcharacters/longestsubstringwithoutrepeatingcharacters.cpp \
    $$PWD/longestsubstringwithoutrepeatingcharacters/test_longestsubstringwithoutrepeatingcharacters.cpp \
    $$PWD/palindromenumber/palindromenumber.cpp \
    $$PWD/palindromenumber/test_palindromenumber.cpp \
    $$PWD/reverseinteger/reverseinteger.cpp \
    $$PWD/reverseinteger/test_reverseinteger.cpp \
    $$PWD/SearchinRotatedSortedArray/SearchinRotatedSortedArray.cpp \
    $$PWD/SearchinRotatedSortedArray/test_SearchinRotatedSortedArray.cpp \
    $$PWD/twosum/test_twosum.cpp \
    $$PWD/twosum/twosum.cpp \
    $$PWD/FindKClosestElements/findkclosestelements.cpp \
    $$PWD/FindKClosestElements/test_findkclosestelements.cpp \
    $$PWD/TopKFrequentElements/topkfrequentelements.cpp \
    $$PWD/TopKFrequentElements/test_topkfrequentelements.cpp \
    $$PWD/NextGreaterElementI/nextgreaterelementi.cpp \
    $$PWD/NextGreaterElementI/test_nextgreaterelementi.cpp \
    $$PWD/GrayCode/graycode.cpp \
    $$PWD/GrayCode/test_graycode.cpp \
    $$PWD/RangeModule/rangemodule.cpp \
    $$PWD/RangeModule/test_rangemodule.cpp \
    $$PWD/RotateImage/rotateimage.cpp \
    $$PWD/RotateImage/test_rotateimage.cpp \
    $$PWD/PlusOne/plusone.cpp \
    $$PWD/RangeModule/test_rangemodule.cpp \
    $$PWD/PlusOne/test_plusone.cpp \
    $$PWD/AddBinary/addbinary.cpp \
    $$PWD/AddBinary/test_addbinary.cpp \
    $$PWD/4Sum/foursum.cpp \
    $$PWD/4Sum/test_foursum.cpp \
    $$PWD/3Sum/testthreesumclass.cpp \
    $$PWD/ReachingPoints/test_reachingpoints.cpp \
    $$PWD/Matrix/matrix.cpp \
    $$PWD/Matrix/test_matrix.cpp \
    $$PWD/1-bitAnd2-bitCharacters/onebitcharactersolution.cpp \
    $$PWD/1-bitAnd2-bitCharacters/test_onebitcharactersolution.cpp \
    $$PWD/132Pattern/pattern132.cpp \
    $$PWD/132Pattern/test_pattern132.cpp \
    $$PWD/GasStation/gasstation.cpp \
    $$PWD/GasStation/test_GasStation.cpp \
    $$PWD/ClimbingStairs/climbingstairs.cpp \
    $$PWD/ClimbingStairs/test_ClimbingStairs.cpp \
    $$PWD/LongestConsecutiveSequence/longestconsecutivesequencesolution.cpp \
    $$PWD/LongestConsecutiveSequence/test_LongestConsecutiveSequence.cpp \
    $$PWD/3SumClosest/threesumclasscloset.cpp \
    $$PWD/3SumClosest/test_3SumClosest.cpp \
    $$PWD/SearchInsertPosition/searchinsertposition.cpp \
    $$PWD/SearchInsertPosition/test_SearchInsertPosition.cpp \
    $$PWD/JumpGame/jumpgame.cpp \
    $$PWD/JumpGame/test_jumpgame.cpp \
    $$PWD/SpiralMatrixII/spiralmatrixii.cpp \
    $$PWD/SpiralMatrixII/test_SpiralMatrixII.cpp \
    $$PWD/SpiralMatrix/spiralmatrix.cpp \
    $$PWD/SpiralMatrix/test_SpiralMatrix.cpp \
    $$PWD/SearchA2DMatrix/searcha2dmatrix.cpp \
    $$PWD/SearchA2DMatrix/test_SearchA2DMatrix.cpp \
    $$PWD/SearchA2DMatrixII/searcha2dmatrixII.cpp \
    $$PWD/SearchA2DMatrixII/test_SearchA2DMatrixII.cpp \
    $$PWD/Subsets/subsets.cpp \
    $$PWD/Subsets/test_Subsets.cpp \
    $$PWD/JumpGameII/jumpgameII.cpp \
    $$PWD/JumpGameII/test_jumpgameII.cpp \
    $$PWD/WordSearch/wordsearch.cpp \
    $$PWD/WordSearch/test_WordSearch.cpp \
    $$PWD/FirstMissingPositive/firstmissingpositive.cpp \
    $$PWD/FirstMissingPositive/test_FirstMissingPositive.cpp \
    $$PWD/MinimumPathSum/minimumpathsum.cpp \
    $$PWD/MinimumPathSum/test_MinimumPathSum.cpp \
    $$PWD/FindMinimumInRotatedSortedArray/findminimuminrotatedsortedarray.cpp \
    $$PWD/FindMinimumInRotatedSortedArray/test_FindMinimumInRotatedSortedArray.cpp \
    $$PWD/FindMinimumInRotatedSortedArrayII/findminimuminrotatedsortedarrayII.cpp \
    $$PWD/FindMinimumInRotatedSortedArrayII/test_FindMinimumInRotatedSortedArrayII.cpp
